---

- name: include os-specific tasks
  include: kibana-Debian.yml
  when: ansible_os_family == 'Debian'

- name: include os-specific tasks
  include: kibana-RedHat.yml
  when: ansible_os_family == 'RedHat'
