---

- name: include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: include kibana.yml
  include: kibana.yml
  tags:
    - install

- name: include kibana-config.yml
  include: kibana-config.yml
  tags:
    - config

- name: Make sure kibana is started
  service:
    name: kibana
    state: started
    enabled: true
