---

- name: include kibana.yml
  include: kibana.yml
  tags:
    - install

- name: include kibana-config.yml
  include: kibana-config.yml
  tags:
    - config

- name: Make sure kibana is started
  service:
    name: kibana
    state: started
    enabled: true
  when: kibana_start_service
